### ISSUE TITLE
세션 만료 에러처리

### ISSUE THREAD

**Issue by ekgns33** [gdsc-konkuk/platform-core#44]
![Screenshot 2024-10-02 at 3 41 57 AM](https://github.com/user-attachments/assets/7fbfae8e-eb4d-4f68-a93e-e8c2314af80e)

어드민 페이지에서 시간이 오래지나면 위 화면이 뜹니다. 뒤로가기해도 계속 발생합니다.

**Comment by ekgns33** [comment]
@goldentrash 확인부탁드려요

**Comment by goldentrash** [comment]
아 알람이 안 떴어서 이제야 확인했네요. 관련 내용은 우선 OCI로 migration 완료 후에 확인해보겠습니다!

**Comment by ekgns33** [comment]
해결되었나요? @goldentrash

**Comment by goldentrash** [comment]
> 해결되었나요? @goldentrash

아, 아직입니다.

개인적인 흥미로라도 원인 분석을 진행 해 볼계획입니다만, 이전 출석 과정에서 활용했던 Google OIDC를 확장해서 로그인에 함께 사용하기로 결정하면서 세션 에러 분석은 우선순위에서 많이 내려온 상황입니다.

**Comment by goldentrash** [comment]
![image](https://github.com/user-attachments/assets/8264c162-f8e1-44c6-9833-6ea06dc36ad8)

화면이 위와 같이 출력되고 있는데, 아무래도 Server 문제보다는 Client 배포 문제로 보입니다.
로그 확인해보니 애초에 `nginx`로도 요청이 안 왔네요.

클라이언트 접속시에 `admin.gdsc-konkuk.dev/`, 즉 site root로 접속하면 접속이 가능한데, `admin.gdsc-konkuk.dev/app`과 같이 하위 페이지로 접속하면 vercel이 mount를 못 해주는거 같습니다.

정확한건 클라이언트쪽에서 분석을 해봐야겠지만, 로그인 후 `app` 하위 페이지로 이동하고, 이후 시간이 흘러 세션이 만료되면 로그인을 위해 리디렉션을 하게 되는 데, 이때 위에서 언급한 하위 page mount(?) 문제로 404가 발생하는것으로 추측합니다.

클라언트 배포 담당자분을 소환해 보지요 @MinboyKim

**Comment by MinboyKim** [comment]
Next.js가 라우팅을 모두 처리해야하는데 Vercel 서버가 하위 패스에 대한 경로를 몰라서 생기는 문제인듯하여 찾아보니 Vercel 관련 config를 처리할 수 있는 `vercel.json` 이라는 파일이 있더군요 [참고](https://vercel.com/docs/projects/project-configuration)

```json
{
  "rewrites": [
    {
      "source": "/(.*)",
      "destination": "/"
    }
  ]
}
```
이렇게 해서 모든 요청을 Next.js의 기본 엔트리 포인트로 리디렉션 시켜 Next.js 라우터가 경로를 처리할 수 있게 해줬습니다 이제 잘 될거에요 아마도.. 저도 Vercel 경험은 많지 않아 어렵네용 하하

**Comment by goldentrash** [comment]
세션 만료 후 정상적으로 `login`으로 리디렉션 확인했습니다!
